feat: fix add pass commit to else condition
Signed-off-by: Allain Magyar <allain.magyar@iohk.io>

diff --git a/.github/workflows/dco.yml b/.github/workflows/dco.yml
--- a/.github/workflows/dco.yml
+++ b/.github/workflows/dco.yml
@@ -25,24 +25,25 @@ jobs:
           fail=0
           dco_check="$(git show --no-patch --format="%B" "$base_sha" | grep 'Signed-off-by:')"
           if [ -z "$dco_check" ]; then
-              echo "Commit $base_sha is missing the DCO sign-off!"
-              fail=1
+            echo "Commit $base_sha is missing the DCO sign-off!"
+            fail=1
+          else
+            echo "$base_sha passed"
           fi
-          echo "$base_sha passed"
-          
           commits="$(git rev-list --ancestry-path $base_sha..$head_sha)"
           for commit in $commits; do
           dco_check="$(git show --no-patch --format="%B" "$commit" | grep 'Signed-off-by:')"
           if [ -z "$dco_check" ]; then
-              printf "\e[31m$commit failed\e[0m\n"
-              fail=1
+            printf "\e[31m$commit failed\e[0m\n"
+            fail=1
+          else
+            echo "$base_sha passed"
           fi
-          echo "$commit passed"
+
           done
-          
           if [ "$fail" -ne 0 ]; then
-              echo "Failures found"
-              exit 1
+            echo "Failures found"
+            exit 1
           fi
           
           echo "---"
